### PR TITLE
Remove async logic

### PR DESCRIPTION
**Pull request by omnivion**
### Information
- JIRA story QPPCT-601.

### Checklist 
- [X] All JUnit tests pass (`mvn clean verify`).
- [X] New unit tests written to cover new functionality.
- [X] Added and updated JavaDocs for non-test classes and methods.
- [X] No local design debt. Do you feel that something is "ugly" after your changes?
- [X] Updated documentation (`README.md`, etc.) depending if the changes require it.

### CODE REVIEW

**Comment by FlexionSonarQube** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [ConcurrencyConfig.java#L3](https://github.com/CMSgov/qpp-conversion-tool/blob/8de6acf65ab8531ca5facbb71da8bf05563e0ff5/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L3): Remove this unused import 'gov.cms.qpp.conversion.api.model.Constants'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ConcurrencyConfig.java#L4](https://github.com/CMSgov/qpp-conversion-tool/blob/8de6acf65ab8531ca5facbb71da8bf05563e0ff5/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L4): Remove this unused import 'org.springframework.beans.factory.annotation.Autowired'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ConcurrencyConfig.java#L7](https://github.com/CMSgov/qpp-conversion-tool/blob/8de6acf65ab8531ca5facbb71da8bf05563e0ff5/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L7): Remove this unused import 'org.springframework.core.env.Environment'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ConcurrencyConfig.java#L10](https://github.com/CMSgov/qpp-conversion-tool/blob/8de6acf65ab8531ca5facbb71da8bf05563e0ff5/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L10): Remove this unused import 'org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sfradkin** [comment]
@omnivion @halprin Also please open a ticket in QPPA asking for the removal of USE_SYNC_EXECUTOR from our S3 env var buckets.

**Comment by FlexionSonarQube** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [ConcurrencyConfig.java#L3](https://github.com/CMSgov/qpp-conversion-tool/blob/1588759cfa74658d9cf74edbea862b7f9a6fd4df/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L3): Remove this unused import 'gov.cms.qpp.conversion.api.model.Constants'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ConcurrencyConfig.java#L4](https://github.com/CMSgov/qpp-conversion-tool/blob/1588759cfa74658d9cf74edbea862b7f9a6fd4df/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L4): Remove this unused import 'org.springframework.beans.factory.annotation.Autowired'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ConcurrencyConfig.java#L7](https://github.com/CMSgov/qpp-conversion-tool/blob/1588759cfa74658d9cf74edbea862b7f9a6fd4df/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L7): Remove this unused import 'org.springframework.core.env.Environment'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ConcurrencyConfig.java#L10](https://github.com/CMSgov/qpp-conversion-tool/blob/1588759cfa74658d9cf74edbea862b7f9a6fd4df/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L10): Remove this unused import 'org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by halprin** [comment]
@sfradkin Will do, but I rather wait until these changes are in the deploy environments so I don't have to explain in the JIRA ticket that Nava can't work on it just yet.

**Comment by FlexionSonarQube** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [ConcurrencyConfig.java#L3](https://github.com/CMSgov/qpp-conversion-tool/blob/2fb34051fa7f7e55e2384f87c70fc40eaac011d9/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L3): Remove this unused import 'gov.cms.qpp.conversion.api.model.Constants'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ConcurrencyConfig.java#L4](https://github.com/CMSgov/qpp-conversion-tool/blob/2fb34051fa7f7e55e2384f87c70fc40eaac011d9/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L4): Remove this unused import 'org.springframework.beans.factory.annotation.Autowired'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ConcurrencyConfig.java#L7](https://github.com/CMSgov/qpp-conversion-tool/blob/2fb34051fa7f7e55e2384f87c70fc40eaac011d9/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L7): Remove this unused import 'org.springframework.core.env.Environment'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)
1. ![MINOR][MINOR] [ConcurrencyConfig.java#L10](https://github.com/CMSgov/qpp-conversion-tool/blob/2fb34051fa7f7e55e2384f87c70fc40eaac011d9/rest-api/src/main/java/gov/cms/qpp/conversion/api/config/ConcurrencyConfig.java#L10): Remove this unused import 'org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AUselessImportCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sfradkin** [comment]
@halprin That's fine.  I just don't want to lose sight of it.  I created QPPCT-604 to track this.

**Pull request merged**
