### PR TITLE
Do a clean when Dockerfiles make the application

### PR DESCRIPTION
**Pull request by halprin**
### Information
- Non-story nor issue improvement.

### Changes proposed in this PR:
- Initiate a clean when building our application in Docker.  This will delete any extraneous files when we copy our application into Docker.
- Saves about 100 MB when sending our Docker image to our small Flexion endpoint.

### Checklist 
- [x] All JUnit tests pass (`mvn clean verify`).
- [x] New unit tests written to cover new functionality.
- [x] Added and updated JavaDocs for non-test classes and methods.
- [x] No local design debt. Do you feel that something is "ugly" after your changes?
- [x] Updated documentation (`README.md`, etc.) depending if the changes require it.

### CODE REVIEW

**Comment by omnivion** [comment]
Well this isn't actually that helpful. From what I know of maven clean plugin, it cleans the directory BEFORE the build, not after, so any file pollution produced by the build will still be there. Does this solve another problem?

**Comment by halprin** [comment]
You are correct that it runs before the build.  This really only applies to the docker build that we run when we do in CircleCI.  In the CircleCI case, we do
1. Our usual `mvn clean verify` as specified in `circle.yml`.
1. Copy all that created stuff into the container as part of the docker build.
1. And finally we do the `mvn clean install` in the docker container.

There could be additional things left over from step 1 that gets copied over in step 2.  That is why in step 3, I added `clean`.

Hmmm, perhaps if I add `mvn clean` once we grab the ReST API after the build...

**Comment by halprin** [comment]
Don't merge this yet.  I still want to tinker with this PR some more.

**Comment by halprin** [comment]
Don't have time to dedicate to this PR at this time.  I'll reopen it when I have time to tinker with this some more.

**Pull request closed without merging**
