### PR TITLE
QPPSF-9315: Warning message update

### PR DESCRIPTION
**Pull request by saquino0827**
### Information
- https://jira.cms.gov/browse/QPPSF-9315

### Changes proposed in this PR:
- Updates Warning message 80 with proper verbiage by program type
- Updates error message 68 with proper verbiage by program type

### Checklist 
- [x] All JUnit tests pass (`mvn clean verify`).
- [x] New unit tests written to cover new functionality.
- [x] Added and updated JavaDocs for non-test classes and methods.
- [x] No local design debt. Do you feel that something is "ugly" after your changes?
- [x] Updated documentation (`README.md`, etc.) depending if the changes require it.

### CODE REVIEW

**Review by shadford — APPROVED** [review]
Looks Good To Me!  Not sure why Checkov is complaining tho...

**Review by KyleApfel — APPROVED** [review]
Looks good!

**Comment by saquino0827** [comment]
> Looks Good To Me! Not sure why Checkov is complaining tho...

Yeah, @rajkpammi should have a ticket in for fixing Checkov.

**Comment by rajkpammi** [comment]
> > Looks Good To Me! Not sure why Checkov is complaining tho...
> 
> Yeah, @rajkpammi should have a ticket in for fixing Checkov.

@shadford checkov scan is complaining on failed policies in the terraform code, i have put in a ticket already - `QPPSF-9309`, will be working on it @saquino0827

**Pull request merged**
